### ISSUE TITLE
Fix 'del' button function

### ISSUE THREAD

**Issue by wogam** [wogam/image-gallery-comfyui#2]
Currently pressing 'del' with multiple items open does not work

**Comment by DadoIrie** [comment]
when images are being deleted via the button in gallery the confirmation is also required (which also works upon confirm and the images are being deleted) but does lead to another issue as you've might figured out, that the image are still being shown on the bottom images list when showing the image in fullscreen and when clicking on the non-existent ones the screen shakes since those images are not present anymore

when hitting the del button (regardless of the count of the images) the confirmation pop-up is showing up and when approving `Uncaught (in promise) TypeError: active is null` is being thrown ;)
